-- Runs the parser and the emitters, then writes the generated files. Only
-- changed headers are reparsed. A header's output depends on its own parse
-- and the scheme alone, so the dependency list does not follow #includes.

import("core.project.depend")
import("utils.progress")
import("xrefl.bases")
import("xrefl.emitter")
import("xrefl.macros")
import("xrefl.paths")
import("xrefl.plan")
import("xrefl.scheme")
import("xrefl.toolchain")
import("xrefl.unit")

-- Rewriting an identical file would recompile everything that includes it.
function _write_if_changed(filepath, content)
    if os.isfile(filepath) and io.readfile(filepath) == content then
        return false
    end
    os.mkdir(path.directory(filepath))
    io.writefile(filepath, content)
    return true
end

function _run_parser(program, target_scheme, units, outdir)
    local argv = {"parse", "--out-dir", outdir, "--root", os.projectdir()}
    local names = scheme.annotation_names(target_scheme)
    if #names > 0 then
        table.insert(argv, "--annotations")
        table.insert(argv, table.concat(names, ","))
    end
    if #target_scheme.ignore_macros > 0 then
        table.insert(argv, "--ignore-macros")
        table.insert(argv, table.concat(target_scheme.ignore_macros, ","))
    end
    for _, item in ipairs(units) do
        table.insert(argv, item.header)
    end

    -- Diagnostics go to the user as is. A "command failed" wrapper would bury
    -- the file and line.
    local errfile = os.tmpfile()
    local code = os.execv(program, argv, {try = true, stdout = os.nuldev(), stderr = errfile})
    local diagnostics = os.isfile(errfile) and io.readfile(errfile) or ""
    os.tryrm(errfile)
    if #diagnostics > 0 then
        io.write(diagnostics)
    end
    if code ~= 0 then
        raise("xrefl: parsing failed")
    end
end

-- How generated code spells an #include of the header: relative to the
-- shortest matching include directory, so it matches what the project writes.
-- Falls back to project-relative, never absolute, so output is reproducible.
function _include_path(target, header)
    local dirs = table.wrap(target:get("includedirs"))
    local best
    for _, dir in ipairs(dirs) do
        local absolute = path.absolute(dir, target:scriptdir())
        local relative = path.relative(header, absolute)
        if relative and not relative:startswith("..") then
            if not best or #relative < #best then
                best = relative
            end
        end
    end
    return path.normalize(best or path.relative(header, os.projectdir())):gsub("\\", "/")
end

-- The aggregate includes every per-header output.
function _aggregate_content(units, extra, include_key, comment)
    local lines = {"// Generated by xrefl. Do not edit.", comment, ""}
    for _, item in ipairs(units) do
        if item[include_key] then
            table.insert(lines, ("#include \"%s\""):format(path.filename(item[include_key])))
        end
    end
    table.insert(lines, "")
    if extra and #extra > 0 then
        table.insert(lines, extra)
    end
    return table.concat(lines, "\n")
end

function _tracked_values(target_scheme, program)
    return {scheme.fingerprint(target_scheme), program, tostring(os.mtime(program))}
end

-- A missing output counts as changed, so a deleted file comes back.
function _changed_units(target, units, values)
    local changed = {}
    for _, item in ipairs(units) do
        local dependfile = target:dependfile(item.source)
        local outputs_present = os.isfile(item.json) and os.isfile(item.source)
        if not outputs_present then
            table.insert(changed, item)
        else
            local dependinfo = depend.load(dependfile) or {}
            if depend.is_changed(dependinfo, {lastmtime = os.mtime(dependfile),
                                              values = values, files = {item.header}}) then
                table.insert(changed, item)
            end
        end
    end
    return changed
end

-- Removes output left behind by headers that no longer match the patterns.
function _remove_stale(target, units, aggregate)
    local keep = {}
    for _, item in ipairs(units) do
        keep[path.normalize(item.source)] = true
        keep[path.normalize(item.include)] = true
        keep[path.normalize(item.json)] = true
    end
    keep[path.normalize(aggregate.source)] = true
    keep[path.normalize(aggregate.include)] = true

    local gendir = paths.gendir(target)
    local candidates = table.join(os.files(path.join(gendir, "*.xrefl.cpp")),
                                  os.files(path.join(gendir, "*.xrefl.h")),
                                  os.files(path.join(gendir, "units", "*.json")))
    for _, file in ipairs(candidates) do
        if not keep[path.normalize(file)] then
            os.tryrm(file)
            os.tryrm(target:dependfile(file))
        end
    end
end

function run(target, opt)
    local target_scheme = scheme.collect(target)
    local units = target:data("xrefl.units") or {}
    local aggregate = target:data("xrefl.aggregate")
    local annotations_header = target:data("xrefl.annotations_header")

    -- Written first, since a target with no headers still needs the macros.
    _write_if_changed(annotations_header.absolute, macros.content(target, target_scheme))

    local payloaddir = target:data("xrefl.payload")
    if payloaddir then
        scheme.publish(target, target_scheme, payloaddir)
    end

    if #units == 0 then
        _write_if_changed(aggregate.source, "// Generated by xrefl. No headers to reflect.\n")
        return
    end
    if #target_scheme.emitters == 0 then
        raise("xrefl: target '%s' has headers to reflect but no emitters.\n" ..
              "  note: add one with reflect_emitter(\"path/to/emit.lua\")", target:name())
    end

    local program = toolchain.find(target)
    local values = _tracked_values(target_scheme, program)
    local changed = _changed_units(target, units, values)

    -- The aggregate also depends on the set of units, not just their contents.
    local stems = {}
    for _, item in ipairs(units) do
        table.insert(stems, item.stem)
    end
    local aggregate_dependfile = target:dependfile(aggregate.source)
    local aggregate_values = table.join(values, {hash.strhash32(table.concat(stems, "\n"))})
    local aggregate_stale = not os.isfile(aggregate.source) or
        depend.is_changed(depend.load(aggregate_dependfile) or {},
                          {lastmtime = os.mtime(aggregate_dependfile),
                           values = aggregate_values, files = {}})

    if #changed == 0 and not aggregate_stale then
        return
    end

    _remove_stale(target, units, aggregate)

    local emitters = emitter.load_all(target_scheme.emitters)
    local outdir = path.join(paths.gendir(target), "units")

    if #changed > 0 then
        progress.show(opt.progress or 0, "${color.build.object}reflecting %d %s in %s",
                      #changed, #changed == 1 and "header" or "headers", target:name())
        _run_parser(program, target_scheme, changed, outdir)
    end

    local regenerate = {}
    for _, item in ipairs(changed) do
        regenerate[item.stem] = true
    end

    -- Every unit is loaded, since the target phase and base matching need all
    -- of them. Only changed ones are emitted again.
    local loaded = {}
    for _, item in ipairs(units) do
        if not os.isfile(item.json) then
            raise("xrefl: the parser produced no unit for %s", item.relative)
        end
        local parsed = unit.load_json(item.json, target_scheme)
        parsed.include_path = _include_path(target, item.header)
        parsed.generated_header = path.filename(item.include)
        item.parsed = parsed
        table.insert(loaded, parsed)
    end
    bases.resolve(loaded)

    for _, item in ipairs(units) do
        local parsed = item.parsed
        if regenerate[item.stem] then
            local out = emitter.run_unit(emitters, parsed)
            local header_written = out.header:used()
            if header_written then
                _write_if_changed(item.include, out.header:content())
            elseif os.isfile(item.include) then
                -- Otherwise the aggregate would still include the old one.
                os.rm(item.include)
            end

            local source = out:content()
            if header_written then
                source = ("#include \"%s\"\n\n"):format(path.filename(item.include)) .. source
            end
            _write_if_changed(item.source, source)

            depend.save({files = {item.header}, values = values},
                        target:dependfile(item.source))
        end
        item.emitted_header = os.isfile(item.include) and item.include or nil
    end

    local target_out = emitter.run_target(emitters, loaded)
    _write_if_changed(aggregate.include,
                      _aggregate_content(units, target_out.header:content(), "emitted_header",
                                         "// Every declaration reflected in this target."))
    _write_if_changed(aggregate.source,
                      ("#include \"%s\"\n\n"):format(path.filename(aggregate.include)) ..
                      target_out:content())
    depend.save({files = {}, values = aggregate_values}, aggregate_dependfile)
end
