-- Generates the header defining the annotation macros. They expand to
-- nothing. The parser reads annotations from the source text.

import("xrefl.scheme")

function content(target, target_scheme)
    local guard = "XREFL_ANNOTATIONS_" .. target:name():upper():gsub("[^%w]", "_") .. "_H"
    local lines = {
        "// Generated by xrefl. Do not edit.",
        "//",
        "// Every macro here expands to nothing. They exist so that annotated",
        "// declarations compile unchanged; the parser reads the annotations",
        "// straight from the source text.",
        "#ifndef " .. guard,
        "#define " .. guard,
        "",
    }
    for _, name in ipairs(scheme.annotation_names(target_scheme)) do
        local declaration = target_scheme.annotations[name]
        if declaration.applies_to then
            local applies = declaration.applies_to
            if type(applies) == "table" then
                applies = table.concat(applies, ", ")
            end
            table.insert(lines, ("// %s: applies to %s"):format(name, applies))
        end
        table.insert(lines, ("#define %s(...)"):format(name))
    end
    table.insert(lines, "")
    table.insert(lines, "#endif  // " .. guard)
    table.insert(lines, "")
    return table.concat(lines, "\n")
end
